version: '3.8'

services:
  fpa-agents:
    build: .
    container_name: fpa-agents-dev
    ports:
      - "8000:8000"
      - "8080:8080"  # ADK web interface
    volumes:
      # Mount source code for live development
      - .:/app
      # Mount data directory
      - ./data:/app/data
      # Mount scratch_pad directory
      - ./scratch_pad:/app/scratch_pad
      # Mount memory directory
      - ./memory:/app/memory
      # Preserve uv cache
      - uv-cache:/tmp/uv-cache
    environment:
      # Load environment variables from .env file
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - FASTAPI_HOST=${FASTAPI_HOST:-0.0.0.0}
      - FASTAPI_PORT=${FASTAPI_PORT:-8000}
      - FASTAPI_DEBUG=${FASTAPI_DEBUG:-True}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    env_file:
      - .env
    networks:
      - fpa-network
    # Restart policy
    restart: unless-stopped
    command: bash -c "cd agents && uv run adk web --host 0.0.0.0 --port 8080"

volumes:
  uv-cache:

networks:
  fpa-network:
    driver: bridge
