version: '3.8'

services:
  # MCP Services Container
  mcp-services:
    build:
      context: ./mcp_tooling
      dockerfile: Dockerfile
    container_name: fpa-mcp-services-prod
    restart: unless-stopped
    # Internal port only - not exposed to host
    expose:
      - "3001"
    # Mount data directories for filesystem access
    volumes:
      - ./data:/mcp-data/data:rw
      - ./scratch_pad:/mcp-data/scratch_pad:rw
      - ./memory:/mcp-data/memory:rw
    # Set environment variables for filesystem server
    environment:
      - FILESYSTEM_SERVER_PORT=3001
      - ALLOWED_DIRECTORIES=/mcp-data/data,/mcp-data/scratch_pad,/mcp-data/memory
      - NODE_ENV=production
    # Health check configuration
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(require('http').get('http://localhost:3001/health').statusCode === 200 ? 0 : 1)"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.2'
          memory: 128M
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  fpa-agents:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: fpa-agents-prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Production environment variables
      - ENVIRONMENT=production
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
      - FASTAPI_DEBUG=false
    env_file:
      - .env.prod
    networks:
      - fpa-network
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Security options
    security_opt:
      - no-new-privileges:true
    # Read-only root filesystem for security
    read_only: true
    # Mount persistent data volumes
    volumes:
      - data-volume:/app/data
      - scratch-pad-volume:/app/scratch_pad
      - memory-volume:/app/memory
    # Temporary filesystems
    tmpfs:
      - /tmp
      - /var/tmp

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: fpa-agents-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - fpa-agents
    networks:
      - fpa-network

networks:
  fpa-network:
    driver: bridge

volumes:
  # Persistent data volumes for production
  data-volume:
  scratch-pad-volume:
  memory-volume:
