version: '3.8'

services:
  fpa-agents:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: fpa-agents-prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Production environment variables
      - ENVIRONMENT=production
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
      - FASTAPI_DEBUG=false
    env_file:
      - .env.prod
    networks:
      - fpa-network
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Security options
    security_opt:
      - no-new-privileges:true
    # Read-only root filesystem for security
    read_only: true
    # Mount persistent data volumes
    volumes:
      - data-volume:/app/data
      - scratch-pad-volume:/app/scratch_pad
      - memory-volume:/app/memory
    # Temporary filesystems
    tmpfs:
      - /tmp
      - /var/tmp

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: fpa-agents-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - fpa-agents
    networks:
      - fpa-network

networks:
  fpa-network:
    driver: bridge

volumes:
  # Persistent data volumes for production
  data-volume:
  scratch-pad-volume:
  memory-volume:
